name: Build and publish Docker image
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out GitHub repo
        uses: actions/checkout@v2
      - name: Log into Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push Docker image
        run: |
          git branch
          docker --version
          time docker build -t garystafford/angular-observe:${{ github.event.release.tag_name }} . --no-cache
          docker image ls | grep 'angular-observe'
          time docker push docker.io/garystafford/angular-observe:${{ github.event.release.tag_name }}
